version: "3"
services:
  serveur_web:
    image: nginx
    volumes:
      - "../:/app"
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - php_fpm
    ports:
      - 8000:80

  php_fpm:
    image: php7.3-fpm-xdebug
    volumes:
      - "../:/app"
      - "./config/php.ini:/usr/local/etc/php/conf.d/custom.ini"
    depends_on:
      - database_service

  database_service:
    image: amd64/mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  mercure_service:
    image: dunglas/mercure
    environment:
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeMe!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeMe!'
      SERVER_NAME: :80
    command:
      caddy run -config /config/Caddyfile
    ports:
      - 3000:80
      - 3443:443
      - 2019:2019
    volumes:
      - "./config/caddy_data:/data"
      - "./config/caddy_config:/config"
      - "../var/log:/mercure_log"